name: cron_schedule

on:
#   schedule:
#     - cron: '0*/10*?**' # is is start my workflow every 10 minute

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Pull the project into the runner
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: Build and run tests
        run: mvn clean test -Dsuite=login