name: Selenoid tests

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull project
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome browser
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f

      - name: Download Chrome WebDriver
        run: |
          CHROME_VERSION=$(google-chrome-stable --version | grep -oP "(?<=Google Chrome )([0-9]+)")
          CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
          wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Start Selenium Server
        run: |
          wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
          CHROME_DRIVER_PATH=$(which chromedriver)
          java -Dwebdriver.chrome.driver="${CHROME_DRIVER_PATH}" -jar selenium-server-standalone-3.141.59.jar &
          sleep 10 # Wait for the server to start

      - name: Run testing
        run: mvn clean test -Dsuite=login
