name: Selenoid tests

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull project
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Start Selenium Server and WebDriver
        run: |
          wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
          java -jar selenium-server-standalone-3.141.59.jar -port 4444 &
          wget https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          echo "export PATH=\$PATH:`pwd`" >> $GITHUB_ENV
          sleep 5

      - name: Run testing
        run: mvn clean test -Dsuite=login
